In [ ]:
# creating n-d arrays
import numpy as np 

In [7]:
# np.array   --> convert list into array
# 1 d array
arr1 = np.array([1,2,3,4])   
arr1

array([1, 2, 3, 4])

In [8]:
type(arr1)

numpy.ndarray

In [12]:
# 2 d array 
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
# n d array just to initallise pass tuples 
# np.zeros(())
arr3 = np.zeros((2,2))
arr3

array([[0., 0.],
       [0., 0.]])

In [17]:
# np.ones(())
arr4 = np.ones((4,4))
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
# np.identity()   --> to create identity matrix 
arr5 = np.identity(4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
arr6 = np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr7 = np.arange(10,20,2)
arr7

array([10, 12, 14, 16, 18])

In [31]:
arr8 = np.linspace(10,20,5)  # give 5 equidistant point between 10 and 20
arr8

array([10. , 12.5, 15. , 17.5, 20. ])

In [34]:
# to copy the privices array
arr9 = arr1.copy()
arr9

array([1, 2, 3, 4])

In [35]:
arr10 = np.full((2,3),7)
arr10

array([[7, 7, 7],
       [7, 7, 7]])

In [36]:
arr11 = np.random.rand(3)
arr11

array([0.46111668, 0.35428324, 0.45731162])

In [38]:
arr12 = np.random.rand(2,3)
arr12

array([[0.5393904 , 0.65518045, 0.4623957 ],
       [0.29601285, 0.63138623, 0.58959238]])

In [41]:
arr13 = np.random.randint(1, 10, size=(5,2))
arr13

array([[8, 2],
       [5, 7],
       [5, 1],
       [6, 1],
       [9, 8]], dtype=int32)