In [1]:
# Proreties and Attributes 
import numpy as np

In [17]:
# ndim 
arr1 = np.array([[[1,2,3],[1,2,3]],[[4,5,6],[4,5,6]]])
arr1

array([[[1, 2, 3],
        [1, 2, 3]],

       [[4, 5, 6],
        [4, 5, 6]]])

In [18]:
arr1.ndim # no. of dim


3

In [19]:
arr1.shape # size of each dim

(2, 2, 3)

In [20]:
arr1.size  # total number of elements

12

In [21]:
arr1.dtype

dtype('int64')

In [22]:
arr1.itemsize # Memory per element 

8

In [23]:
arr1.nbytes # total memory use

96

In [26]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
arr2.T  # Transpose

array([[1, 4],
       [2, 5],
       [3, 6]])