In [2]:
# NumPy Operations 
import numpy as np

In [3]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [4]:
arr1+arr2

array([5, 7, 9])

In [5]:
arr1-arr2

array([-3, -3, -3])

In [6]:
arr2/arr1

array([4. , 2.5, 2. ])

In [7]:
arr2%arr1

array([0, 1, 0])

In [8]:
arr1**arr2

array([  1,  32, 729])

In [9]:
# scaler operation
arr1+1

array([2, 3, 4])

In [10]:
arr2*2

array([ 8, 10, 12])

In [11]:
arr1>2

array([False, False,  True])

In [13]:
# Mathematical Functions
np.sqrt(arr2)

array([2.        , 2.23606798, 2.44948974])

In [14]:
np.log(arr1)

array([0.        , 0.69314718, 1.09861229])

In [15]:
np.sum(arr1)

np.int64(6)

In [16]:
arr3 = np.array([7,2,8])

In [17]:
np.sort(arr3)

array([2, 7, 8])

In [19]:
# shape operation   --> dimensions
np.shape(arr3)

(3,)

In [20]:
arr4 = np.array([[1,2,3],[4,5,6]])
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
np.shape(arr4)

(2, 3)

In [67]:
# reshaping operations  --> changing shape without changing data
arr5 = np.array([1,2,3,4,5,6,7,8])
arr5

array([1, 2, 3, 4, 5, 6, 7, 8])

In [68]:
arr5.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [69]:
arr5.reshape(4,-1)  # Auto calculate dimension

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [6]:
import numpy as np

In [10]:
arr6 = np.array([[1,2,3,4],[5,6,7,8]])
arr6

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
arr6.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
arr6

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr6.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [16]:
# stacking
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [17]:
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [26]:
arr3 = np.vstack((arr1,arr2))
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
# spliting 
arr1

array([1, 2, 3])

In [28]:
np.hsplit(arr1,3)

[array([1]), array([2]), array([3])]

In [29]:
np.vsplit(arr3,2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [30]:
arr3.flatten()

array([1, 2, 3, 4, 5, 6])