In [14]:
# indexing 
import numpy as np
arr = np.arange(5,50)
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [15]:
print(arr[2])

7


In [16]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
print(arr1[1,1])

5


In [29]:
arr2 = np.array([[[1, 2],[3, 4]],[[5, 6],[7, 8]]])
arr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [32]:
print(arr2[1,1,1])

8


In [33]:
# Slicing
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [34]:
arr[1:7]

array([ 6,  7,  8,  9, 10, 11])

In [36]:
arr[10:]

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49])

In [43]:
print(arr1[:, 0:1])

[[1]
 [4]]


In [44]:
# iteration 
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [45]:
for i in arr:
    print(i)

5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49


In [48]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
for row in arr1:
    print(row)


[1 2 3]
[4 5 6]


In [53]:
for i in np.nditer(arr1):
    print(i)

1
2
3
4
5
6
